// <auto-generated />
using System;
using LetPot.Platform.u202416903.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LetPot.Platform.u202416903.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717043806_AddTelemetryDataRecord")]
    partial class AddTelemetryDataRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LetPot.Platform.u202416903.Allocation.Domain.Model.Aggregate.Pot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("customerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("macAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mac_address");

                    b.Property<double>("preferredHumidityLevel")
                        .HasColumnType("double")
                        .HasColumnName("preferred_humidity_level");

                    b.HasKey("Id")
                        .HasName("p_k_pots");

                    b.ToTable("pots");
                });

            modelBuilder.Entity("LetPot.Platform.u202416903.Telemetry.Domain.Model.Aggregate.DataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<double>("currentHumidityLevel")
                        .HasColumnType("double")
                        .HasColumnName("current_humidity_level");

                    b.Property<DateTime>("emittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("emitted_at");

                    b.Property<int>("operationMode")
                        .HasColumnType("int")
                        .HasColumnName("operation_mode");

                    b.Property<int>("operationPhase")
                        .HasColumnType("int")
                        .HasColumnName("operation_phase");

                    b.Property<string>("potMacAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pot_mac_address");

                    b.Property<double>("targetHumidityLevel")
                        .HasColumnType("double")
                        .HasColumnName("target_humidity_level");

                    b.HasKey("Id")
                        .HasName("p_k_data_records");

                    b.ToTable("data_records");
                });
#pragma warning restore 612, 618
        }
    }
}
